---

- name: FUNCTION - get_checksums - Download Consul Checksums
  get_url: url='{{ _consul_agent_checksums_url }}' dest='/tmp'
  register: _external_dependency_success
  until: _external_dependency_success|success
  retries: '{{ external_dependency_retries }}'
  delay: '{{ external_dependency_delay }}'

- name: FUNCTION - get_checksums - Get Consul Agent Checksum
  shell: >
    cat '/tmp/{{ _consul_agent_checksums_name }}' |
    grep '{{ _consul_agent_archive_name }}' | awk '{print $1}'
  register: _consul_agent_archive_checksum

- name: FUNCTION - get_checksums - Remove Consul Checksum artifacts
  file: name='/tmp/{{ _consul_agent_checksums_name }}' state=absent
